import Providers from "@/lib/Providers";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Meddic - Hospital Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        {/* add favicon */}

        <body
          className={`${inter.className} max-w-[1920px] mx-auto  bg-bgColor`}
        >
          {children}
        </body>
      </html>
    </Providers>
  );
}
