import Providers from "@/lib/Providers";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer/Footer";
import { Layout } from "antd";
import DashboardSiteBar from "@/components/dashboard/DashboardSiteBar/DashboardSiteBar";
import DashboardContents from "@/components/dashboard/DashboardContent/DashboardContent";

export const metadata: Metadata = {
  title: "Meddic - Hospital Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Layout hasSider>
      <DashboardSiteBar />
      <DashboardContents>{children}</DashboardContents>
    </Layout>
  );
}
